site_name: Dns v2.0.9+20210319
site_url: http://byron.github.io/google-apis-rs/google-dns1-cli
site_description: A complete library to interact with Dns (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/dns1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['changes_create.md', 'Changes', 'Create']
- ['changes_get.md', 'Changes', 'Get']
- ['changes_list.md', 'Changes', 'List']
- ['dns-keys_get.md', 'Dns Keys', 'Get']
- ['dns-keys_list.md', 'Dns Keys', 'List']
- ['managed-zone-operations_get.md', 'Managed Zone Operations', 'Get']
- ['managed-zone-operations_list.md', 'Managed Zone Operations', 'List']
- ['managed-zones_create.md', 'Managed Zones', 'Create']
- ['managed-zones_delete.md', 'Managed Zones', 'Delete']
- ['managed-zones_get.md', 'Managed Zones', 'Get']
- ['managed-zones_list.md', 'Managed Zones', 'List']
- ['managed-zones_patch.md', 'Managed Zones', 'Patch']
- ['managed-zones_update.md', 'Managed Zones', 'Update']
- ['policies_create.md', 'Policies', 'Create']
- ['policies_delete.md', 'Policies', 'Delete']
- ['policies_get.md', 'Policies', 'Get']
- ['policies_list.md', 'Policies', 'List']
- ['policies_patch.md', 'Policies', 'Patch']
- ['policies_update.md', 'Policies', 'Update']
- ['projects_get.md', 'Projects', 'Get']
- ['projects_managed-zones-rrsets-create.md', 'Projects', 'Managed Zones Rrsets Create']
- ['projects_managed-zones-rrsets-delete.md', 'Projects', 'Managed Zones Rrsets Delete']
- ['projects_managed-zones-rrsets-get.md', 'Projects', 'Managed Zones Rrsets Get']
- ['projects_managed-zones-rrsets-patch.md', 'Projects', 'Managed Zones Rrsets Patch']
- ['resource-record-sets_list.md', 'Resource Record Sets', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

